### ISSUE TITLE
Many errors in the code

### ISSUE THREAD

**Issue by iyupan** [erichson/LipschitzRNN#2]
Thanks for the kind of you to publish the code. However, there could be many errors, for example:
- in `models.py`
<img width="490" alt="截屏2021-06-28 11 05 56" src="https://user-images.githubusercontent.com/58758269/123573773-214a0c80-d801-11eb-8d21-ff556efce75e.png">
the "<<<<< HEAD", "=====" and ">>>>>>> 5f48c091283b460b3b3957e8beaf34a0416670ec" make trouble.

- in `driver.py`
<img width="439" alt="截屏2021-06-28 11 10 37" src="https://user-images.githubusercontent.com/58758269/123573929-7dad2c00-d801-11eb-993d-f56507418e2e.png">
rnn_models seems lost.

I really don't know how to solve these problems. Could you help me?

**Comment by erichson** [comment]
@perryuu thank you for spotting this! It seems, that I introduced some issues last time I pushed updates. But, everything is fixed now. Can you please do a pull or a fresh clone of the repository and try to run the model?

Best,
Ben

**Comment by iyupan** [comment]
> @perryuu thank you for spotting this! It seems, that I introduced some issues last time I pushed updates. But, everything is fixed now. Can you please do a pull or a fresh clone of the repository and try to run the model?
> 
> Best,
> Ben

Haha，really thanks for your help!
